---
---
###RII2001
```{r}
library(dplyr)
library(haven)
library(plyr)
library(tidyr)
library(stringr)

df2000 <- read_sav(file = "RI2000.sav")
df2001 <- read_sav(file = "RII2001.sav")

df2000 %>%
  filter(id %in% df2001$id)%>%
  select(id, grad_y, grad, indust, occu, workfor, workers, workplace, workhrs, wage, fwork_indust, fwork_occu, fworkfor, fwage, marry, Sbirth_y, Sedu, Sindust, Soccu, Sworkfor, Sworkers, Sworkplace, Sworkhrs, Swage)->df20
merge(df2001,df20,by="id",all.x=TRUE)->df21
names(df21)
name<-c("id","grad_y","grad","fwork_indust","fwork_occu","fworkfor","fwage","Sworkers","Sworkplace")

df21$indust<-ifelse(df21$c01b==1,
df21$indust.y,df21$indust.x)
df21$occu<-ifelse(df21$c01b==1,
df21$occu.y,df21$occu.x)
df21$workfor<-ifelse(df21$c01b==1,
df21$workfor.y,df21$workfor.x)
df21$workers<-ifelse(df21$c01b==1,
df21$workers.y,df21$workers.x)
df21$workplace<-ifelse(df21$c01b==1,
df21$workplace.y,df21$workplace.x)
df21$workhrs<-ifelse(df21$c01b==1,
df21$workhrs.y,df21$workhrs.x)
df21$wage<-ifelse(df21$c01b==1,
df21$wage.y,df21$wage.x)
df21$marry <- ifelse((df21$c21a==2), df21$marry.y, df21$marry.x)
df21$Sbirth_y <- ifelse((df21$c21a==1), df21$Sbirth_y.y, df21$Sbirth_y.x)
df21$Sedu <- ifelse((df21$c21a==1),
df21$Sedu.y, df21$Sedu.x)
df21$Sindust <- ifelse((df21$c26b==1),
df21$Sindust.y,df21$Sbirth_y.x)
df21$Soccu <- ifelse((df21$c26b==1),
df21$Soccu.y,df21$Soccu.x)
df21$Sworkfor <- ifelse((df21$c26b==1),
df21$Sworkfor.y,df21$Sworkfor.x)
df21$Sworkhrs <- ifelse((df21$c26b==1),
df21$Sworkhrs.y,df21$Sworkhrs.x)
df21$Swage <- ifelse((df21$c26b==1),
df21$Swage.y,df21$Swage.x)
names(df21)
dropname<- c(11:21,24:29,41,43,46:52,57:62,65:66)
dropname
select(df21,-c(dropname))->testdf
names(testdf)

write_sav(testdf,"RII2001_new.sav")



full_join(df1999, df2000, df2001, all.=TRUE)->df1920
```

###RIII2001
```{r}
df1999 <- read_sav(file = "RI1999.sav")
df2001b <- read_sav(file = "RIII2001.sav")

df1999 %>%
  filter(id %in% df2001b$id) %>%
  select(id, male, birth_y, edu, grad_y, grad, indust, occu, workfor, workers, workplace, workhrs, wage, fwork_y, fwork_indust, fwork_occu, fworkfor, fwage, marry, Sbirth_y, Sedu, Sindust, Soccu, Sworkfor, Sworkers, Sworkplace, Sworkhrs, Swage)->df19
merge(df2001b,df19,by="id",all.x=TRUE)->df201
names(df201)
df201$indust<-ifelse(df201$a03b==1,
df201$indust.y,df201$indust.x)
df201$occu<-ifelse(df201$a03b==1,
df201$occu.y,df201$occu.x)
df201$workfor<-ifelse(df201$a03b==1,
df201$workfor.y,df201$workfor.x)
df201$workhrs<-ifelse(df201$a03b==1,
df201$workhrs.y,df201$workhrs.x)
df201$wage<-ifelse(df201$a03b==1,
df201$wage.y,df201$wage.x)
df201$marry <- ifelse((df201$a11a==2), df201$marry.y, df201$marry.x)
df201$Sbirth_y <- ifelse((df201$a11a==1), df201$Sbirth_y.y, df201$Sbirth_y.x)
df201$Sedu <- ifelse((df201$a11a==1),
df201$Sedu.y, df201$Sedu.x)
df201$Sindust<-ifelse(df201$a16b==1,
df201$Sindust.y,df201$Sindust.x)
df201$Soccu<-ifelse(df201$a16b==1,
df201$Soccu.y,df201$Soccu.x)
df201$Sworkfor<-ifelse(df201$a16b==1,
df201$Sworkfor.y,df201$Sworkfor.x)
df201$Sworkhrs<-ifelse(df201$a16b==1,
df201$Sworkhrs.y,df201$Sworkhrs.x)
df201$Swage<-ifelse(df201$a16b==1,
df201$Swage.y,df201$Swage.x)

names(df201)
dropname<-c(8:16,19:24,32,39:41,44:45,51:56,59:60)
select(df201,-c(dropname))->testdf

write_sav(testdf,"RIII2001_new.sav")
### go to SPSS to combine two files of 2001 and call it RR2001_new.sav.
```

```{r}
df2001 <- read_sav(file = "RR2001_new.sav")
df2002 <- read_sav(file = "RR2002.sav")

table(df2001$Sedu)
table(df2002$scale)
df2001 %>%
  filter(id %in% df2002$id) %>%
  select(id, male, birth_y, edu, grad_y, grad, indust, occu, workfor, workers, workplace, workhrs, wage, fwork_y, fwork_indust, fwork_occu, fworkfor, fwage, marry, Sbirth_y, Sedu, Sindust, Soccu, Sworkfor, Sworkers, Sworkplace, Sworkhrs, Swage)->df21

merge(df2002,df21,by="id",all.x=TRUE)->df22
names(df22)
df22$indust<-ifelse(df22$a03b04==1,
df22$indust.y,df22$indust.x)
df22$occu<-ifelse(df22$a03b04==1,
df22$occu.y,df22$occu.x)
df22$workfor<-ifelse(df22$a03b04==1,
df22$workfor.y,df22$workfor.x)
df22$workers<-ifelse(df22$a03b04==1,
df22$workers.y,df22$workers.x)
df22$workplace<-ifelse(df22$a03b04==1,
df22$workplace.y,df22$workplace.x)
df22$workhrs<-ifelse(df22$a03b04==1,
df22$workhrs.y,df22$workhrs.x)
df22$wage<-ifelse(df22$a03b04==1,
df22$wage.y,df22$wage.x)
df22$marry <- ifelse((df22$a14==2), df22$marry.y, df22$marry.x)
df22$Sbirth_y <- ifelse((df22$a14==1), df22$Sbirth_y.y, df22$Sbirth_y.x)
df22$Sedu <- ifelse((df22$a14==1),
df22$Sedu.y, df22$Sedu.x)
df22$Sindust <- ifelse((df22$a19b04==1),
df22$Sindust.y,df22$Sbirth_y.x)
df22$Soccu <- ifelse((df22$a19b04==1),
df22$Soccu.y,df22$Soccu.x)
df22$Sworkfor <- ifelse((df22$a19b04==1),
df22$Sworkfor.y,df22$Sworkfor.x)
df22$Sworkers<-ifelse(df22$a19b04==1,
df22$Sworkers.y,df22$Sworkers.x)
df22$Sworkplace<-ifelse(df22$a19b04==1,
df22$Sworkplace.y,df22$Sworkplace.x)
df22$Sworkhrs<-ifelse(df22$a19b04==1,
df22$Sworkhrs.y,df22$Sworkhrs.x)
df22$Swage<-ifelse(df22$a19b04==1,
df22$Swage.y,df22$Swage.x)
names(df22)

dropname<-c(9:16,18:20,23:30,38,44:50,56:65)
select(df22, -c(dropname)) -> testdf

write_sav(testdf,"RR2002_new.sav")
```

```{r}
df2003 <- read_sav(file = "RR2003.sav")
df2002 <- read_sav(file = "RR2002_new.sav")

table(df2002$Sedu)
sum(is.na(df2003$marry))
sum(is.na(testdf$marry))
table(df22$indust.x)
table(testdf$indust)
df2002 %>%
  filter(id %in% df2003$id) %>%
  select(id, scale, birth_y, edu, grad_y, grad, indust, occu, workfor, workers, workplace, workhrs, wage, fwork_y, fwork_indust, fwork_occu, fworkfor, fwage, housework, marry, Sbirth_y, Sedu, Sindust, Soccu, Sworkfor, Sworkers, Sworkplace, Sworkhrs, Swage, Shousework)->df21

merge(df2003,df21,by="id",all.x=TRUE)->df22
names(df22)

df22$indust<-ifelse(df22$indust.x==0,
df22$indust.y,df22$indust.x)
df22$occu<-ifelse(df22$occu.x==0,
df22$occu.y,df22$occu.x)
df22$workfor<-ifelse(df22$workfor.x==0,
df22$workfor.y,df22$workfor.x)
df22$workers<-ifelse(df22$workers.x==0,
df22$workers.y,df22$workers.x)
df22$workplace<-ifelse(df22$workplace.x==0,
df22$workplace.y,df22$workplace.x)
df22$workhrs<-ifelse(df22$workers.x==0,
df22$workhrs.y,df22$workhrs.x)
df22$wage<-ifelse(df22$workers.x==0,
df22$wage.y,df22$wage.x)
df22$marry <- ifelse(is.na(df22$marry.x), df22$marry.y, df22$marry.x)
df22$Sbirth_y <- ifelse((df22$marry==3 | df22$marry==2), df22$Sbirth_y, 0)
df22$Sedu <- ifelse((df22$marry==3 | df22$marry==2),
df22$Sedu, 0)
df22$Sindust <- ifelse((df22$Sindust.x==0),
df22$Sindust.y,df22$Sindust.x)
df22$Soccu <- ifelse((df22$Soccu.x==0),
df22$Soccu.y,df22$Soccu.x)
df22$Sworkfor <- ifelse((df22$Sworkfor.x==0),
df22$Sworkfor.y,df22$Sworkfor.x)
df22$Sworkers<-ifelse(df22$Sworkers.x==0,
df22$Sworkers.y,df22$Sworkers.x)
df22$Sworkplace<-ifelse(df22$Sworkplace.x==0,
df22$Sworkplace.y,df22$Sworkplace.x)
df22$Sworkhrs<-ifelse(df22$Sworkers.x==0,
df22$Sworkhrs.y,df22$Sworkhrs.x)
df22$Swage<-ifelse(df22$Sworkers.x==0,
df22$Swage.y,df22$Swage.x)
names(df22)
dropname<-c(7:13,15,17:23,29:35,42,45:51)
select(df22, -c(dropname))->testdf

write_sav(testdf,"RR2003_new.sav")
### go to SPSS to combine two files of 2003 and call it RR2003_new2.sav.
```

```{r}
df2003b <- read_sav(file = "RR2003_new2.sav")
df2004 <- read_sav(file = "RR2004.sav")


sum(is.na(df2004$marry))
table(df2004$marry)
table(df2003$marry)
sum(is.na(df2003$marry))
table(df22$marry)
df2003 %>%
  filter(id %in% df2004$id) %>%
  select(id, male, birth_y, edu, grad_y, grad, fwork_y, fwork_indust, fwork_occu, fworkfor, fwage, marry, Sbirth_y, Sedu)->df21

merge(df2004,df21,by="id",all.x=TRUE)->df22
names(df22)

table(df22$Sbirth_y.x)
table(df22$Sbirth_y)
table(df22$Sedu.x)
table(df22$Sedu)
table(df22$marry.y)
sum(is.na(df2003$marry))
sum(is.na(df22$marry.y))

table(df2004$marry)
table(df22$marry)
sum(is.na(df22$marry))
sum(is.na(df22$Sbirth_y.y))
sum(is.na(df22$Sbirth_y.x))
sum(is.na(df22$Sbirth_y))
df22$marry <- ifelse(df22$marry.x==0, df22$marry.y, df22$marry.x)
df22$Sbirth_y <- ifelse((df22$marry==3 & is.na(df22$Sbirth_y.x)), df22$Sbirth_y.y, df22$Sbirth_y.x)
df22$Sedu <- ifelse((df22$marry==3 & df22$Sedu.x==0),
df22$Sedu.y, df22$Sedu.x)
names(df22)
dropname <- c(19:21,50,61:63)
select(df22, -c(dropname))->testdf
names(testdf)
write_sav(testdf, "RR2004_new.sav")
```

```{r}
df2004 <- read_sav(file = "RR2004_new.sav")
df2005 <- read_sav(file = "RR2005.sav")


sum(is.na(df2004$marry))
table(df2004$marry)
sum(is.na(df2005$marry))
table(df2005$marry)
table(df2001$workhrs)

df2004 %>%
  filter(id %in% df2005$id) %>%
  select(id, male, birth_y, edu, grad_y, grad, indust, occu, workfor, workers, workplace, fwork_y, fwork_indust, fwork_occu, fworkfor, fwage, Sbirth_y, Sedu, Sindust, Soccu, Sworkfor, Sworkers, Sworkplace)->df21

merge(df2005,df21,by="id",all.x=TRUE)->df22
names(df22)

table(df22$Sbirth_y.x)
sum(is.na(df22$Sedu.x))
table(df22$Sedu.x)
table(df22$indust.x)
table(df22$a11b04)
table(df22$work)

df22$indust<-ifelse(df22$a11b04==1,
df22$indust.y,df22$indust.x)
table(df22$indust)
df22$occu<-ifelse(df22$a11b04==1,
df22$occu.y,df22$occu.x)
df22$workfor<-ifelse(df22$a11b04==1,
df22$workfor.y,df22$workfor.x)
df22$workers<-ifelse(df22$a11b04==1,
df22$workers.y,df22$workers.x)
df22$workplace<-ifelse(df22$a11b04==1,
df22$workplace.y,df22$workplace.x)

table(df22$Sbirth_y.x)
table(df22$Sbirth_y)
table(df22$Sedu.x)
table(df22$Sedu)
df22$Sbirth_y <- ifelse((df22$marry==3 & is.na(df22$Sbirth_y.x)), df22$Sbirth_y.y, df22$Sbirth_y.x)
df22$Sedu <- ifelse((df22$marry==3 & df22$Sedu.x==0),
df22$Sedu.y, df22$Sedu.x)


df22$Sindust <- ifelse((df22$a27b04==1),
df22$Sindust.y,df22$Sindust.x)
df22$Soccu <- ifelse((df22$a27b04==1),
df22$Soccu.y,df22$Soccu.x)
df22$Sworkfor <- ifelse((df22$a27b04==1),
df22$Sworkfor.y,df22$Sworkfor.x)
df22$Sworkers<-ifelse(df22$a27b04==1,
df22$Sworkers.y,df22$Sworkers.x)
df22$Sworkplace<-ifelse(df22$a27b04==1,
df22$Sworkplace.y,df22$Sworkplace.x)

names(df22)
dropname<-c(9:14,21:22,25:30,64:68,74:80)
select(df22, -c(dropname))->testdf
names(testdf)
write_sav(testdf,"RR2005_new.sav")
```

```{r}
df2005 <- read_sav(file = "RR2005_new.sav")
df2006 <- read_sav(file = "RR2006.sav")


table(df2005$Sbirth_y)
table(df2006$Sbirth_y)
table(df2006$marry)
df2005 %>%
  filter(id %in% df2006$id) %>%
  select(id, edu, grad_y, grad, fwork_y, fwork_indust, fwork_occu, fworkfor, fwage)->df21
merge(df2006,df21,by="id",all.x=TRUE)->df22

write_sav(df22,"RR2006_new.sav")
```

```{r}
df2006 <- read_sav(file = "RR2006_new.sav")
df2007 <- read_sav(file = "RR2007.sav")

df2006 %>%
  filter(id %in% df2007$id) %>%
  select(id, edu, grad_y, grad, workfor, workers, indust, occu, fwork_y, fwork_indust, fwork_occu, fworkfor, fwage, Sworkfor, Sworkers, Sindust, Soccu)->df21

merge(df2007,df21,by="id",all.x=TRUE)->df22

df22$workfor <- ifelse((df22$a06z03==1 | df22$a06z04==1 | df22$a06z05==1 | df22$a06z06==1),
  df22$workfor.y, df22$workfor.x)
df22$workers <- ifelse((df22$a06z03==1 | df22$a06z04==1 | df22$a06z05==1 | df22$a06z06==1),
  df22$workers.y, df22$workers.x)
df22$indust <- ifelse((df22$a06z05==1 | df22$a06z06==1),
  df22$indust.y, df22$indust.x)
df22$occu <- ifelse((df22$a06z05==1 | df22$a06z06==1),
  df22$occu.y, df22$occu.x)

df22$Sworkfor <- ifelse((df22$a21b03==1 | df22$a21b03==1 | df22$a21b05==1 | df22$a21b06==1),
  df22$Sworkfor.y, df22$Sworkfor.x)
df22$Sworkers <- ifelse((df22$a21b03==1 | df22$a21b04==1 | df22$a21b05==1 | df22$a21b06==1),
  df22$Sworkers.y, df22$Sworkers.x)
df22$Sindust <- ifelse((df22$a21b05==1 | df22$a21b06==1),
  df22$Sindust.y, df22$Sindust.x)
df22$Soccu <- ifelse((df22$a21b05==1 | df22$a21b06==1),
  df22$Soccu.y, df22$Soccu.x)

dropname <- c(14:17,27:30,63:70,80:83,89:92)
select(df22,-c(dropname))->testdf

write_sav(testdf,"RR2007_new.sav")
```

```{r}
df2007 <- read_sav(file = "RR2007_new.sav")
df2008 <- read_sav(file = "RR2008.sav")


df2007 %>%
  filter(id %in% df2008$id) %>%
  select(id, edu, grad_y, grad, workfor, workers, indust, occu, fwork_y, fwork_indust, fwork_occu, fworkfor, fwage, Sworkfor, Sworkers, Sindust, Soccu)->df21

merge(df2008,df21,by="id",all.x=TRUE)->df22

df22$workfor <- ifelse((df22$a06z03==1 | df22$a06z04==1 | df22$a06z05==1 | df22$a06z06==1),
  df22$workfor.y, df22$workfor.x)
df22$workers <- ifelse((df22$a06z03==1 | df22$a06z04==1 | df22$a06z05==1 | df22$a06z06==1),
  df22$workers.y, df22$workers.x)
df22$indust <- ifelse((df22$a06z05==1 | df22$a06z06==1),
  df22$indust.y, df22$indust.x)
df22$occu <- ifelse((df22$a06z05==1 | df22$a06z06==1),
  df22$occu.y, df22$occu.x)

df22$Sworkfor <- ifelse((df22$a21b03==1 | df22$a21b03==1 | df22$a21b05==1 | df22$a21b06==1),
  df22$Sworkfor.y, df22$Sworkfor.x)
df22$Sworkers <- ifelse((df22$a21b03==1 | df22$a21b04==1 | df22$a21b05==1 | df22$a21b06==1),
  df22$Sworkers.y, df22$Sworkers.x)
df22$Sindust <- ifelse((df22$a21b05==1 | df22$a21b06==1),
  df22$Sindust.y, df22$Sindust.x)
df22$Soccu <- ifelse((df22$a21b05==1 | df22$a21b06==1),
  df22$Soccu.y, df22$Soccu.x)


dropname<-c(14:17,30:33,64:71,81:84,90:93)
select(df22, -c(dropname))->testdf
write_sav(testdf,"RR2008_new.sav")

```


```{r}
df2008 <- read_sav(file = "RR2008_new.sav")
df2009 <- read_sav(file = "RR2009.sav")


df2008 %>%
  filter(id %in% df2009$id) %>%
  select(id, grad_y, grad, workfor, workers, indust, occu, fwork_y, fwork_indust, fwork_occu, fworkfor, fwage, Sworkfor, Sworkers, Sindust, Soccu)->df21

merge(df2009,df21,by="id",all.x=TRUE)->df22

df22$workfor <- ifelse((df22$a06z03==1 | df22$a06z04==1 | df22$a06z05==1 | df22$a06z06==1),
  df22$workfor.y, df22$workfor.x)
df22$workers <- ifelse((df22$a06z03==1 | df22$a06z04==1 | df22$a06z05==1 | df22$a06z06==1),
  df22$workers.y, df22$workers.x)
df22$indust <- ifelse((df22$a06z05==1 | df22$a06z06==1),
  df22$indust.y, df22$indust.x)
df22$occu <- ifelse((df22$a06z05==1 | df22$a06z06==1),
  df22$occu.y, df22$occu.x)

df22$Sworkfor <- ifelse((df22$a21z03==1 | df22$a21z03==1 | df22$a21z05==1 | df22$a21z06==1),
  df22$Sworkfor.y, df22$Sworkfor.x)
df22$Sworkers <- ifelse((df22$a21z03==1 | df22$a21z04==1 | df22$a21z05==1 | df22$a21z06==1),
  df22$Sworkers.y, df22$Sworkers.x)
df22$Sindust <- ifelse((df22$a21z05==1 | df22$a21z06==1),
  df22$Sindust.y, df22$Sindust.x)
df22$Soccu <- ifelse((df22$a21z05==1 | df22$a21z06==1),
  df22$Soccu.y, df22$Soccu.x)

dropname<-c(15:18,30:31,33:34,76:83,92:95,101:104)
select(df22, -c(dropname))->testdf
write_sav(testdf,"RR2009_new.sav")
### go to SPSS to combine two files of 2009 and call it RR2009_new2.sav.
```

```{r}
df2009 <- read_sav(file = "RR2009_new2.sav")
df2010 <- read_sav(file = "RR2010.sav")


df2009 %>%
  filter(id %in% df2010$id) %>%
  select(id, grad_y, grad, workfor, workers, indust, occu, fwork_y, fwork_indust, fwork_occu, fworkfor, fwage, Sworkfor, Sworkers, Sindust, Soccu)->df21

merge(df2010,df21,by="id",all.x=TRUE)->df22
df22$workfor <- ifelse(
  (df22$a06z03==1 | df22$a06z04==1 | df22$a06z05==1 | df22$a06z06==1),
    df22$workfor.y, df22$workfor.x)
df22$workers <- ifelse(
  (df22$a06z03==1 | df22$a06z04==1 | df22$a06z05==1 | df22$a06z06==1),
    df22$workers.y, df22$workers.x)
df22$indust <- ifelse(
  (df22$a06z05==1 | df22$a06z06==1),
    df22$indust.y, df22$indust.x)
df22$occu <- ifelse(
  (df22$a06z05==1 | df22$a06z06==1),
    df22$occu.y, df22$occu.x)

df22$Sworkfor <- ifelse(
  (df22$a21z03==1 | df22$a21z03==1 | df22$a21z05==1 | df22$a21z06==1),
    df22$Sworkfor.y, df22$Sworkfor.x)
df22$Sworkers <- ifelse(
  (df22$a21z03==1 | df22$a21z04==1 | df22$a21z05==1 | df22$a21z06==1),
    df22$Sworkers.y, df22$Sworkers.x)
df22$Sindust <- ifelse(
  (df22$a21z05==1 | df22$a21z06==1),
    df22$Sindust.y, df22$Sindust.x)
df22$Soccu <- ifelse(
  (df22$a21z05==1 | df22$a21z06==1),
    df22$Soccu.y, df22$Soccu.x)

names(df22)
dropname<-c(15:18,31:34,64:71,80:83,89:92)
select(df22, -c(dropname))->testdf
write_sav(testdf,"RR2010_new.sav")
```

```{r}
df2010 <- read_sav(file = "RR2010_new.sav")
df2011 <- read_sav(file = "RR2011.sav")


df2010 %>%
  filter(id %in% df2011$id) %>%
  select(id, grad_y, grad, workfor, workers, indust, occu, fwork_y, fwork_indust, fwork_occu, fworkfor, fwage, myear, Sbirth_y, Sworkfor, Sworkers, Sindust, Soccu)->df21

merge(df2011,df21,by="id",all.x=TRUE)->df22
df22$workfor <- ifelse(
  (df22$a06z03==1 | df22$a06z04==1 | df22$a06z05==1 | df22$a06z06==1),
    df22$workfor.y, df22$workfor.x)
df22$workers <- ifelse(
  (df22$a06z03==1 | df22$a06z04==1 | df22$a06z05==1 | df22$a06z06==1),
    df22$workers.y, df22$workers.x)
df22$indust <- ifelse(
  (df22$a06z05==1 | df22$a06z06==1),
    df22$indust.y, df22$indust.x)
df22$occu <- ifelse(
  (df22$a06z05==1 | df22$a06z06==1),
    df22$occu.y, df22$occu.x)

table(df2011$myear)
table(df22$myear)
table(df2010$myear)
table(df2011$Sbirth_y)
table(df22$Sbirth_y)
table(df2010$Sbirth_y)
df22$myear <- ifelse(
  (df22$a16a==1 | df22$a16a==2),
    df22$myear.y, df22$myear.x)
df22$Sbirth_y <- ifelse(
  (df22$a16a==1 | df22$a16a==2),
    df22$Sbirth_y.y, df22$Sbirth_y.x)


df22$Sworkfor <- ifelse(
  (df22$a21z03==1 | df22$a21z03==1 | df22$a21z05==1 | df22$a21z06==1),
    df22$Sworkfor.y, df22$Sworkfor.x)
df22$Sworkers <- ifelse(
  (df22$a21z03==1 | df22$a21z04==1 | df22$a21z05==1 | df22$a21z06==1),
    df22$Sworkers.y, df22$Sworkers.x)
df22$Sindust <- ifelse(
  (df22$a21z05==1 | df22$a21z06==1),
    df22$Sindust.y, df22$Sindust.x)
df22$Soccu <- ifelse(
  (df22$a21z05==1 | df22$a21z06==1),
    df22$Soccu.y, df22$Soccu.x)

names(df22)
dropname<-c(15:18,26:27,31:34,64:72,81:84,90:95)
select(df22,-c(dropname))->testdf

write_sav(testdf,"RR2011_new.sav")
```

```{r}
df2011 <- read_sav(file = "RR2011_new.sav")
df2012 <- read_sav(file = "RR2012.sav")

df2011 %>%
  filter(id %in% df2011$id) %>%
  select(id, grad_y, grad, workfor, workers, indust, occu, fwork_y, fwork_indust, fwork_occu, fworkfor, fwage, myear, Sbirth_y, Sworkfor, Sworkers, Sindust, Soccu)->df21

merge(df2012,df21,by="id",all.x=TRUE)->df22
df22$workfor <- ifelse(
  (df22$a06z03==1 | df22$a06z04==1 | df22$a06z05==1 | df22$a06z06==1),
    df22$workfor.y, df22$workfor.x)
df22$workers <- ifelse(
  (df22$a06z03==1 | df22$a06z04==1 | df22$a06z05==1 | df22$a06z06==1),
    df22$workers.y, df22$workers.x)
df22$indust <- ifelse(
  (df22$a06z05==1 | df22$a06z06==1),
    df22$indust.y, df22$indust.x)
df22$occu <- ifelse(
  (df22$a06z05==1 | df22$a06z06==1),
    df22$occu.y, df22$occu.x)

table(df2012$myear)
table(df22$myear)
table(df2011$myear)
table(df2012$Sbirth_y)
table(df22$Sbirth_y)
table(df2011$Sbirth_y)
df22$myear <- ifelse(
  (df22$a16a==1 | df22$a16a==2),
    df22$myear.y, df22$myear.x)
df22$Sbirth_y <- ifelse(
  (df22$a16a==1 | df22$a16a==2),
    df22$Sbirth_y.y, df22$Sbirth_y.x)

table(df2012$Sworkfor)
table(df22$Sworkfor)
df22$Sworkfor <- ifelse(
  (df22$a21z03==1 | df22$a21z03==1 | df22$a21z05==1 | df22$a21z06==1),
    df22$Sworkfor.y, df22$Sworkfor.x)
df22$Sworkers <- ifelse(
  (df22$a21z03==1 | df22$a21z04==1 | df22$a21z05==1 | df22$a21z06==1),
    df22$Sworkers.y, df22$Sworkers.x)
df22$Sindust <- ifelse(
  (df22$a21z05==1 | df22$a21z06==1),
    df22$Sindust.y, df22$Sindust.x)
df22$Soccu <- ifelse(
  (df22$a21z05==1 | df22$a21z06==1),
    df22$Soccu.y, df22$Soccu.x)

names(df22)
dropname<-c(14:17,25:26,30:33,63:71,81:84,90:95)
select(df22,-c(dropname))->testdf
write_sav(testdf,"RR2012_new.sav")
```

```{r}
df2012 <- read_sav(file = "RR2012_new.sav")
df2014 <- read_sav(file = "RR2014.sav")

df2012 %>%
  filter(id %in% df2014$id) %>%
  select(id, grad_y, grad, fwork_y, fwork_indust, fwork_occu, fworkfor, fwage, myear, Sbirth_y, Sedu)->df21

merge(df2014,df21,by="id",all.x=TRUE)->df22

df22$myear <- ifelse(
  (df22$a16a==1 | df22$a16a==2),
    df22$myear.y, df22$myear.x)
df22$Sbirth_y <- ifelse(
  (df22$a16a==1 | df22$a16a==2),
    df22$Sbirth_y.y, df22$Sbirth_y.x)
df22$Sedu <- ifelse(
  (df22$a16a==1 | df22$a16a==2),
    df22$Sedu.y, df22$Sedu.x)
names(df22)
dropname<-c(87:89,73,26:28)
select(df22, -all_of(dropname))->testdf
write_sav(testdf,"RR2014_new.sav")
```

```{r}
df2014 <- read_sav(file = "RR2014_new.sav")
df2016 <- read_sav(file = "RR2016.sav")

df2014 %>%
  filter (id %in% df2016$id) %>%
  select(id, grad_y, grad, fwork_y, fwork_indust, fwork_occu, fworkfor, fwage)->df21
merge(df2016,df21,by="id",all.x=TRUE)->df22

names(df22)
dropname<-c(80:82,25)
select(df22, -all_of(dropname))->testdf
write_sav(testdf,"RR2016_new.sav")
```

```{r}
df2016 <- read_sav(file = "RR2016_new2.sav")
df2018 <- read_sav(file = "RR2018.sav")

df2016 %>%
  filter(id %in% df2018$id) %>%
  select(id, grad_y, Sedu,myear)->df21
merge(df2018, df21, by="id", all.x=TRUE)->df22

df22$myear<- ifelse(df22$a17a==2 & df22$a17b==2 |
                      df22$a17d==1 & df22$a17e==2,
                    df22$myear.y, df22$myear.x)
df22$Sedu<- ifelse(df22$a17a==2 & df22$a17b==2 |
                      df22$a17d==1 & df22$a17e==2,
                    df22$Sedu.y, df22$Sedu.x)
names(df22)
dropname<-c(37,38,40,88:90,98,99)
select(df22, -all_of(dropname))->testdf
write_sav(testdf, "RR2018_new.sav")
```

```{r}
df2018 <- read_sav(file = "RR2018_new.sav")
df2020 <- read_sav(file = "RR2020.sav")
df2020 %>%
  filter(id %% 10 == 0)->df2

df2018 %>%
  filter(id %in% df2$id) %>%
  select(id, myear, Sbirth_y)->df21
merge(df2, df21, by="id", all.x = TRUE)->df22

df22$myear <- ifelse(is.na(df22$myear.x)&df22$w20a==2, df22$myear.y,df22$myear.x)
df22$Sbirth_y <- ifelse(is.na(df22$Sbirth_y.x)&df22$w20a==2, df22$Sbirth_y.y,df22$Sbirth_y.x)

names(df22)
dropname <- c(84,85,81,82,77)
select(df22, -all_of(dropname))->testdf
names(testdf)
write_sav(testdf,"RR2020_new.sav")
```

```{r}
df2001 <- read_sav(file = "RR2001_new.sav")
df2002 <- read_sav(file = "RR2002_new.sav")
df2003 <- read_sav(file = "RR2003_new.sav")
df2004 <- read_sav(file = "RR2004_new.sav")
df2005 <- read_sav(file = "RR2005_new.sav")
df2006 <- read_sav(file = "RR2006_new.sav")
df2007 <- read_sav(file = "RR2007_new.sav")
df2008 <- read_sav(file = "RR2008_new.sav")
df2009 <- read_sav(file = "RR2009_new.sav")
df2010 <- read_sav(file = "RR2010_new.sav")
df2011 <- read_sav(file = "RR2011_new.sav")
df2012 <- read_sav(file = "RR2012_new.sav")
df2014 <- read_sav(file = "RR2014_new.sav")
df2016 <- read_sav(file = "RR2016_new.sav")
df2018 <- read_sav(file = "RR2018_new.sav")
df2020 <- read_sav(file = "RR2020_new.sav")

NNN <- function(x){
  sum(is.na(x$Sindust))
}
NNN(df2001)
NNN(df2002)
NNN(df2003)
NNN(df2004)
NNN(df2005)
NNN(df2006)
NNN(df2007)
NNN(df2008)
NNN(df2009)
NNN(df2010)
NNN(df2011)
NNN(df2012)
NNN(df2014)
NNN(df2016)
NNN(df2018)
NNN(df2020)






```



















